### ISSUE TITLE
num_threads configuration for prediction

### ISSUE THREAD

**Issue by geohardtke** [Mottl/lightgbm3-rs#1]
Hi,
I used and provided some minor fixes to the previous iterations of this crate, and I'm glad someone is updating it again! I use lightgbm.predict  inside a rayon thread pool and noticed that predict uses more cpus than I requested in rayon. After some testing I found that defining the parameter as "num_threads=1" in line 110 which is currently just and empty string, does the trick.
Would be nice to add the option to configure that, and maybe the other parameters as well. Happy to implement it if you are willing to take PRs!
Cheers

**Comment by Mottl** [comment]
Hi, thanks for the suggestion. Fixed with 84173c47 and v1.0.3

**Comment by Mottl** [comment]
Yes, you can pass multiple parameters for prediction separated by space (e.g. `"param1=value1 param2=value2 param3=value"`), but I haven't experimented with them.
