### ISSUE TITLE
Is `Booster` thread safe?

### ISSUE THREAD

**Issue by tokahuke** [Mottl/lightgbm3-rs#6]
So, I have run into the problem that `Booster` is neither `Send` nor `Sync`, since it contains some naughty pointers inside. However, most of the operations it seems to be doing look inherently immutable. Would it be sound to add `unsafe impl`'s for `Send` and `Sync` for `Booster`?

**Comment by Mottl** [comment]
Hi! I'm not sure that `Booster` is thread safe (at minimum, while training).
If you believe it's absolutely necessary for you to have `Send` or `Sync`, and your use case is thread safe, you can just implement a wrapper for `Booster`.
```rust
struct WBooster(Booster);
unsafe impl Send for WBooster {}
unsafe impl Sync for WBooster {}
```

**Comment by tokahuke** [comment]
Well, that is what I am doing at the moment. Fortunately, for my use case,
I only need the evaluation part (an immutable operation). I can see,
however, that it is has no reason to be threadsafe for training.

Em sáb., 10 de ago. de 2024 às 09:39, Dmitry Mottl ***@***.***>
escreveu:
