### ISSUE TITLE
Is it possible to increase feature_name_length?

### ISSUE THREAD

**Issue by Veiasai** [Mottl/lightgbm3-rs#9]
```   
 pub fn feature_name(&self) -> Result<Vec<String>> {
        let num_feature = self.inner_num_features()?;
        let feature_name_length = 32;
```

32 is relatively small... I have some features that have longer name..
I am not sure if the C API has max limit on length?

**Comment by Mottl** [comment]
Yes, for sure. Just upgrade to the latest version of the crate
